"""
test_homology.py

Tests comparing homologous genes on k-mer content
"""
from click.testing import CliRunner
import os
from io import StringIO

import pandas as pd
import pandas.util.testing as pdt
import pytest


@pytest.fixture(params=['protein_coding_peptide', 'protein_coding_cdna',
                        'protein_coding_cds', 'non_coding',
                        pytest.mark.xfail("asdfasdf")])
def datatype(request):
    return request.param


@pytest.fixture
def species1():
    return 'human'


@pytest.fixture
def species2():
    return 'chicken'


@pytest.fixture
def homologues_tsv(data_folder):
    return os.path.join(data_folder, 'homology',
                        'human-chicken-orthologs-subset.tsv')

@pytest.fixture
def homologues_tsv_gz(data_folder):
    return os.path.join(data_folder, 'homology',
                        'human-chicken-orthologs-subset.tsv.gz')

@pytest.fixture
def homologues(homologues_tsv):
    return pd.read_csv(homologues_tsv, sep='\t')


@pytest.fixture
def homologues_bad_iput(homologues_tsv):
    return pd.read_csv(homologues_tsv)


@pytest.fixture
def homology_scores_allpairs_csv(data_folder):
    return os.path.join(data_folder, 'homology',
                        'human-chicken-orthologs-subset-kmer-homology-scores'
                        '__allpairs_nbackground2.csv')


@pytest.fixture
def homology_scores_allpairs(homology_scores_allpairs_csv):
    return pd.read_csv(homology_scores_allpairs_csv)


class TestHomologyTable:

    @pytest.fixture
    def homology_table(self, species1, species2, homologues):
        from khtools.homology import HomologyTable

        return HomologyTable(homologues, species1, species2)

    def test___init__(self, species1, species2, homology_table):
        test = homology_table

        assert test.species1 == species1
        assert test.species2 == species2
        assert test.species1_id_col == 'Query protein or transcript ID'
        assert test.species2_id_col == \
               'Chicken protein or transcript stable ID'
        assert test.homology_type_col == 'Chicken homology type'
        assert test.quantitative_features == \
               ['%id. target Chicken gene identical to query gene',
                '%id. query gene identical to target Chicken gene',
                'Chicken Gene-order conservation score',
                'Chicken Whole-genome alignment coverage',
                'dN with Chicken', 'dS with Chicken']
        assert test.protein_coding.shape == (11, 21)
        assert test.non_coding.shape == (9, 21)

    def test___init___bad_input(self, species1, species2, homologues_bad_iput):
        from khtools.homology import HomologyTable
        with pytest.raises(ValueError):
            HomologyTable(homologues_bad_iput, species1, species2)

    def test_get_sequences_from_ids_protein(self, homology_table):
        test = homology_table.get_sequences_from_ids(
            homology_table.protein_coding, homology_table.species1_id_col,
            'protein', 'protein')
        assert test == [('ENSP00000439937',
                         'MSTAREQPIFSTRAHVFQIDPATKRNWIPAGKHALTVSYFYDATRNVYRIISIGGAKAIINSTVTPNMTFTKTSQKFGQWADSRANTVYGLGFASEQHLTQFAEKFQEVKEAARLAREKSQDGGELTSPALGLASHQVPPSPLVSANGPGEEKLFRSQSADAPGPTERERLKKMLSEGSVGEVQWEAEFFALQDSNNKLAGALREANAAAAQWRQQLEAQRAEAERLRQRVAELEAQAASEVTPTGEKEGLGQGQSLEQLEALVQTKDQEIQTLKSQTGGPREALEAAEREETQQKVQDLETRNAELEHQLRAMERSLEEARAERERARAEVGRAAQLLDVSLFELSELREGLARLAEAAP'),
                        ('ENSP00000419413',
                         'MACLLETPIRMSVLSEVTASSRHYVDRLFDPDPQKVLQGVIDMKNAVIGNNKQKANLIVLGAVPRLLYLLQQETSSTELKTECAVVLGSLAMGTENNVKSLLDCHIIPALLQGLLSPDLKFIEACLRCLRTIFTSPVTPEELLYTDATVIPHLMALLSRSRYTQEYICQIFSHCCKGPDHQTILFNHGAVQNIAHLLTSLSYKVRMQALKCFSVLAFENPQVSMTLVNVLVDGELLPQIFVKMLQRDKPIEMQLTSAKCLTYMCRAGAIRTDDNCIVLKTLPCLVRMCSKERLLEERVEGAETLAYLIEPDVELQRIASITDHLIAMLADYFKYPSSVSAITDIKRLDHDLKHAHELRQAAFKLYASLGANDEDIRKKIIETENMMDRIVTGLSESSVKVRLAAVRCLHSLSRSVQQLRTSFQDHAVWKPLMKVLQNAPDEILVVASSMLCNLLLEFSPSKEPILESGAVELLCGLTQSENPALRVNGIWALMNMAFQAEQKIKADILRSLSTEQLFRLLSDSDLNVLMKTLGLLRNLLSTRPHIDKIMSTHGKQIMQAVTLILEGEHNIEVKEQTLCILANIADGTTAKDLIMTNDDILQKIKYYMGHSHVKLQLAAMFCISNLIWNEEEGSQERQDKLRDMGIVDILHKLSQSPDSNLCDKAKMALQQYLA'),
                        ('ENSP00000323036',
                         'MRAAPLLLARAASLSLGFLFLLFFWLDRSVLAKELKFVTLVFRHGDRSPIDTFPTDPIKESSWPQGFGQLTQLGMEQHYELGEYIRKRYRKFLNESYKHEQVYIRSTDVDRTLMSAMTNLAALFPPEGVSIWNPILLWQPIPVHTVPLSEDQLLYLPFRNCPRFQELESETLKSEEFQKRLHPYKDFIATLGKLSGLHGQDLFGIWSKVYDPLYCESVHNFTLPSWATEDTMTKLRELSELSLLSLYGIHKQKEKSRLQGGVLVNEILNHMKRATQIPSYKKLIMYSAHDTTVSGLQMALDVYNGLLPPYASCHLTELYFEKGEYFVEMYYRNETQHEPYPLMLPGCSPSCPLERFAELVGPVIPQDWSTECMTTNSHQVLKVIFAVAFCLISAVLMVLLFIHIRRGLCWQRESYGNI'),
                        ('ENSP00000416050',
                         'MVLGGCPVSYLLLCGQAALLLGNLLLLHCVSRSHSQNATAEPELTSAGAAQPEGPGGAASWEYGDPHSPVILCSYLPDEFIECEDPVDHVGNATASQELGYGCLKFGGQAYSDVEHTSVQCHALDGIECASPRTFLRENKPCIKYTGHYFITTLLYSFFLGCFGVDRFCLGHTGTAVGKLLTLGGLGIWWFVDLILLITGGLMPSDGSNWCTVY'),
                        ('ENSP00000265978',
                         'MERMNWLSRLASRGPGHRIPQGANLQTPVMADPETCLMVFKNHWSQVVRILERQGPRAAPGGADDLSAVRNHTYQMLTLLAEDRAVPSAPTGPGPLLEFALHEDLLTRVLTWQLQWDELGDGVEERRAEQLKLFEMLVSEARQPLLRHGPVREALLTLLDACGRPVPSSPALDEGLVLLLSQLCVCVAQEPSLLEFFLQPPPEPGAAPRLLLFSRLVPFVHREGTLGQQARDALLLLMALSAGSPTVGRYIADHSYFCPVLATGLSALYSSLPRKIEVPGDDWHCLRREDWLGVPALALFMSSLEFCNAVIQVAHPLVQKQLVDYIHNGFLVPVMGPALHKTSVEEMIASTAYLELFLRSISEPALLRTFLRFLLLHRHDTHTILDTLVARIGSNSRLCMVSLSLFRTLLNLSCEDVLLQLVLRYLVPCNHVMLSQKPAVRDVDLYGRAADKFLSLIPRCCRHHAPSPPRPEHASWARGGPSRETGRREDITGPGSPSVDSSSVTTVPRPSTPSRLALFLRQQSLGGSESPGPAPCSPGLSASPASSPGRRPTPAEEPGELEDNYLEYLREARRGVDRCVRACRTWSAPYDGERPSPEPSPFGSRTKKRSLLPEEDRNNVGEGEEEELGRRGRAGGAGEGPGHLPPPQLNGVPGSWPEGAKKVRLVPKEGAGELLEGISEGMAGLEGFGQELRELEVALSNGGTGSESPLEPPLPLEEEEAYESFTCPPEPPGPFLSSPLRTLNQLPSQPFTGPFMAVLFAKLENMLQNSVYVNFLLTGLVAQLACHPQPLLRSFLLNTNMVFQPSVKSLLQVLGSVKNKIENFAASQEDFPALLSKAKKYLIARGKLDWAEGPAAGPAPRRSDPLVKSRRPSLGELLLRHAHSPTRARQAAQLVLQPGRDGAGLGLSGGSPGASTPVLLTRGGAPERQGEALRVKNAVYCAVIFPEFLKELAAISQAHAVTSPFLLETSEEGSGPLISGCGPLNP'),
                        ('ENSP00000329127',
                         'MSSGTMKFNGYLRVRIGEAVGLQPTRWSLRHSLFKKGHQLLDPYLTVSVDQVRVGQTSTKQKTNKPTYNEEFCANVTDGGHLELAVFHETPLGYDHFVANCTLQFQELLRTTGASDTFEGWVDLEPEGKVFVVITLTGSFTEATLQRDRIFKHFTRKRQRAMRRRVHQINGHKFMATYLRQPTYCSHCREFIWGVFGKQGYQCQVCTCVVHKRCHHLIVTACTCQNNINKVDSKIAEQRFGINIPHKFSIHNYKVPTFCDHCGSLLWGIMRQGLQCKICKMNVHIRCQANVAPNCGVNAVELAKTLAGMGLQPGNISPTSKLVSRSTLRRQGKESSKEGNGIGVNSSNRLGIDNFEFIRVLGKGSFGKVMLARVKETGDLYAVKVLKKDVILQDDDVECTMTEKRILSLARNHPFLTQLFCCFQTPDRLFFVMEFVNGGDLMFHIQKSRRFDEARARFYAAEIISALMFLHDKGIIYRDLKLDNVLLDHEGHCKLADFGMCKEGICNGVTTATFCGTPDYIAPEILQEMLYGPAVDWWAMGVLLYEMLCGHAPFEAENEDDLFEAILNDEVVYPTWLHEDATGILKSFMTKNPTMRLGSLTQGGEHAILRHPFFKEIDWAQLNHRQIEPPFRPRIKSREDVSNFDPDFIKEEPVLTPIDEGHLPMINQDEFRNFSYVSPELQP'),
                        ('ENSP00000438264',
                         'MASVFHYFLLVLVFLDTHAAQPFCLPGCTCSEESFGRTLQCTSVSLGKIPGNLSEEFKQVRIENSPLFEMPQGSFINMSTLEYLWLNFNNISVIHLGALEHLPELRELRLEGNKLCSVPWTAFRATPLLRVLDLKRNKIDALPELALQFLVSLTYLDLSSNRLTVVSKSVFLNWPAYQKCRQPDCGAEILSSLVVALHDNPWVCDCRLRGLVQFVKSITLPVILVNSYLICQGPLSKAGQLFHETELSACMKPQISTPSANITIRAGQNVTLRCLAQASPSPSIAWTYPLSMWREFDGLLGGKHLTPVLTSSTGEDTALSELAIPAAHLVDSGNYTCMASNSIGKSNLVISLHVQPAQALHAPDSLSIPSEGNAYIDLRVVKQTVHGILLEWLAVADTSKEEWFTLYIASDEAFRKEVVHIGPGINTYAVDDLLPGTKYEACLSLEGQPPHQGQCVAFVTGRDAGGLEAREHLLHVTVVLCVVLLAVPVGAYAWAAQGPCSCSKWVLRGCLHRRKAPSCTPAAPQSKDGSFREHPAVCDDGEGHIDTEGDKEKGGTEDNS'),
                        ('ENSP00000298552',
                         'MAQQANVGELLAMLDSPMLGVRDDVTAVFKENLNSDRGPMLVNTLVDYYLETSSQPALHILTTLQEPHDKHLLDRINEYVGKAATRLSILSLLGHVIRLQPSWKHKLSQAPLLPSLLKCLKMDTDVVVLTTGVLVLITMLPMIPQSGKQHLLDFFDIFGRLSSWCLKKPGHVAEVYLVHLHASVYALFHRLYGMYPCNFVSFLRSHYSMKENLETFEEVVKPMMEHVRIHPELVTGSKDHELDPRRWKRLETHDVVIECAKISLDPTEASYEDGYSVSHQISARFPHRSADVTTSPYADTQNSYGCATSTPYSTSRLMLLNMPGQLPQTLSSPSTRLITEPPQATLWSPSMVCGMTTPPTSPGNVPPDLSHPYSKVFGTTAGGKGTPLGTPATSPPPAPLCHSDDYVHISLPQATVTPPRKEERMDSARPCLHRQHHLLNDRGSEEPPGSKGSVTLSDLPGFLGDLASEEDSIEKDKEEAAISRELSEITTAEAEPVVPRGGFDSPFYRDSLPGSQRKTHSAASSSQGASVNPEPLHSSLDKLGPDTPKQAFTPIDLPCGSADESPAGDRECQTSLETSIFTPSPCKIPPPTRVGFGSGQPPPYDHLFEVALPKTAHHFVIRKTEELLKKAKGNTEEDGVPSTSPMEVLDRLIQQGADAHSKELNKLPLPSKSVDWTHFGGSPPSDEIRTLRDQLLLLHNQLLYERFKRQQHALRNRRLLRKVIKAAALEEHNAAMKDQLKLQEKDIQMWKVSLQKEQARYNQLQEQRDTMVTKLHSQIRQLQHDREEFYNQSQELQTKLEDCRNMIAELRIELKKANNKVCHTELLLSQVSQKLSNSESVQQQMEFLNRQLLVLGEVNELYLEQLQNKHSDTTKEVEMMKAAYRKELEKNRSHVLQQTQRLDTSQKRILELESHLAKKDHLLLEQKKYLEDVKLQARGQLQAAESRYEAQKRITQVFELEILDLYGRLEKDGLLKKLEEEKAEAAEAAEERLDCCNDGCSDSMVGHNEEASGHNGETKTPRPSSARGSSGSRGGGGSSSSSSELSTPEKPPHQRAGPFSSRWETTMGEASASIPTTVGSLPSSKSFLGMKARELFRNKSESQCDEDGMTSSLSESLKTELGKDLGVEAKIPLNLDGPHPSPPTPDSVGQLHIMDYNETHHEHS'),
                        ('ENSP00000454973',
                         'MMASFQRSNSHDKVRRIVAEEGRTARNLIAWSVPLESKDDDGKPKCQTGGKSKRTIQGTHKTTKQSTAVDCKITSSTTGDKHFDKSPTKTRHPRKIDLRARYWAFLFDNLRRAVDEIYVTCESDQSVVECKEVLMMLDNYVRDFKALIDWIQLQEKLEKTDAQSRPTSLAWEVKKMSPGRHVIPSPSTDRINVTSNARRSLNFGGSTGTVPAPRLAPTGVSWADKVKAHHTGSTASSEITPAQSCPPMTVQKASRKNERKDAEGWETVQRGRPIRSRSTAVMPKVSLATEATRSKDDSDKENVCLLPDESIQKGQFVGDGTSNTIESHPKDSLHSCDHPLAEKTQFTVSTLDDVKNSGSIRDNYVRTSEISAVHIDTECVSVMLQAGTPPLQVNEEKFPAEKARIENEMDPSDISNSMAEVLAKKEELADRLEKANEEAIASAIAEEEQLTREIEAEENNDINIETDNDSDFSASMGSGSVSFCGMSMDWNDVLADYEARESWRQNTSWGDIVEEEPARPPGHGIHMHEKLSSPSRKRTIAESKKKHEEKQMKAQQLREKLREEKTLKLQKLLEREKDVRKWKEELLDQRRRMMEEKLLHAEFKREVQLQAIVKKAQEEEAKVNEIAFINTLEAQNKRHDVLSKLKEYEQRLNELQEERQRRQEEKQARDEAVQERKRALEAERQARVEELLMKRKEQEARIEQQRQEKEKAREDAARERARDREERLAALTAAQQEAMEELQKKIQLKHDESIRRHMEQIEQRKEKAAELSSGRHANTDYAPKLTPYERKKQCSLCNVLISSEVYLFSHVKGRKHQQAVRENTSIQGRELSDEEVEHLSLKKYIIDIVVESTAPAEALKDGEERQKNKKKAKKIKARMNFRAKEYESLMETKNSGSDSPYKAKLQRLAKDLLKQVQVQDSGSWANNKVSALDRTLGEITRILEKENVADQIAFQAAGGLTALEHILQAVVPATNVNTVLRIPPKSLCNAINVYNLTCNNCSENCSDVLFSNKITFLMDLLIHQLTVYVPDENNTILGRNTNKQVFEGLTTGLLKVSAVVLGCLIANRPDGNCQPATPKIPTQEMKNKPSQGDPFNNRVQDLISYVVNMGLIDKLCACFLSVQGPVDENPKMAIFLQHAAGLLHAMCTLCFAVTGRSYSIFDNNRQDPTGLTAALQATDLAGVLHMLYCVLFHGTILDPSTASPKENYTQNTIQVAIQSLRFFNSFAALHLPAFQSIVGAEGLSLAFRHMASSLLGHCSQVSCESLLHEVIVCVGYFTVNHPDNQVIVQSGRHPTVLQKLCQLPFQYFSDPRLIKVLFPSLIAACYNNHQNKIILEQEMSCVLLATFIQDLAQTPGQAENQPYQPKGKCLGSQDYLELANRFPQQAWEEARQFFLKKEKK'),
                        ('ENSP00000466399',
                         'MGVLRVGLCPGLTEEMIQLLRSHRIKTVVDLVSADLEEVAQKCGLSYKTWRAHSSGNLGGLQLPQVPAGRSWSGVRNALKKAGLGHGGTDGLSLNAFDERGTAVSTSRLDKLLDAGLYTGEVTEIVGGPGSGKTQVCLCMAANVAHGLQQNVLYVDSNGGLTASRLLQLLQAKTQDEEEQAEALRRIQVVHAFDIFQMLDVLQELRGTVAQQVTGSSGTVKVVVVDSVTAVVSPLLGGQQREGLALMMQLARELKTLARDLGMAVVVTNHITRDRDSGRLKPALGRSWSFVPSTRILLDTIEGAGASGGRRMACLAKSSRQPTGFQEMVDIGTWGTSEQSATLQGDQT'),
                        ('ENSP00000338130',
                         'MAVFKTTLWRLISGTLGIICLSLMSTLGILLKNSFTKLSIEPAFTPGPNIELQKDSDCCSCQEKWVGYRCNCYFISSEQKTWNESRHLCASQKSSLLQLQNTDELDFMSSSQQFYWIGLSYSEEHTAWLWENGSALSQYLFPSFETFNTKNCIAYNPNGNALDESCEDKNRYICKQQLI')]

    def test_get_sequences_from_ids_noncoding(self, homology_table):
        test = homology_table.get_sequences_from_ids(
            homology_table.protein_coding, homology_table.species1_id_col,
            'DNA', 'cdna')
        assert test == [('ENSP00000439937',
                         'MSTAREQPIFSTRAHVFQIDPATKRNWIPAGKHALTVSYFYDATRNVYRIISIGGAKAIINSTVTPNMTFTKTSQKFGQWADSRANTVYGLGFASEQHLTQFAEKFQEVKEAARLAREKSQDGGELTSPALGLASHQVPPSPLVSANGPGEEKLFRSQSADAPGPTERERLKKMLSEGSVGEVQWEAEFFALQDSNNKLAGALREANAAAAQWRQQLEAQRAEAERLRQRVAELEAQAASEVTPTGEKEGLGQGQSLEQLEALVQTKDQEIQTLKSQTGGPREALEAAEREETQQKVQDLETRNAELEHQLRAMERSLEEARAERERARAEVGRAAQLLDVSLFELSELREGLARLAEAAP'),
                        ('ENSP00000419413',
                         'MACLLETPIRMSVLSEVTASSRHYVDRLFDPDPQKVLQGVIDMKNAVIGNNKQKANLIVLGAVPRLLYLLQQETSSTELKTECAVVLGSLAMGTENNVKSLLDCHIIPALLQGLLSPDLKFIEACLRCLRTIFTSPVTPEELLYTDATVIPHLMALLSRSRYTQEYICQIFSHCCKGPDHQTILFNHGAVQNIAHLLTSLSYKVRMQALKCFSVLAFENPQVSMTLVNVLVDGELLPQIFVKMLQRDKPIEMQLTSAKCLTYMCRAGAIRTDDNCIVLKTLPCLVRMCSKERLLEERVEGAETLAYLIEPDVELQRIASITDHLIAMLADYFKYPSSVSAITDIKRLDHDLKHAHELRQAAFKLYASLGANDEDIRKKIIETENMMDRIVTGLSESSVKVRLAAVRCLHSLSRSVQQLRTSFQDHAVWKPLMKVLQNAPDEILVVASSMLCNLLLEFSPSKEPILESGAVELLCGLTQSENPALRVNGIWALMNMAFQAEQKIKADILRSLSTEQLFRLLSDSDLNVLMKTLGLLRNLLSTRPHIDKIMSTHGKQIMQAVTLILEGEHNIEVKEQTLCILANIADGTTAKDLIMTNDDILQKIKYYMGHSHVKLQLAAMFCISNLIWNEEEGSQERQDKLRDMGIVDILHKLSQSPDSNLCDKAKMALQQYLA'),
                        ('ENSP00000323036',
                         'MRAAPLLLARAASLSLGFLFLLFFWLDRSVLAKELKFVTLVFRHGDRSPIDTFPTDPIKESSWPQGFGQLTQLGMEQHYELGEYIRKRYRKFLNESYKHEQVYIRSTDVDRTLMSAMTNLAALFPPEGVSIWNPILLWQPIPVHTVPLSEDQLLYLPFRNCPRFQELESETLKSEEFQKRLHPYKDFIATLGKLSGLHGQDLFGIWSKVYDPLYCESVHNFTLPSWATEDTMTKLRELSELSLLSLYGIHKQKEKSRLQGGVLVNEILNHMKRATQIPSYKKLIMYSAHDTTVSGLQMALDVYNGLLPPYASCHLTELYFEKGEYFVEMYYRNETQHEPYPLMLPGCSPSCPLERFAELVGPVIPQDWSTECMTTNSHQVLKVIFAVAFCLISAVLMVLLFIHIRRGLCWQRESYGNI'),
                        ('ENSP00000416050',
                         'MVLGGCPVSYLLLCGQAALLLGNLLLLHCVSRSHSQNATAEPELTSAGAAQPEGPGGAASWEYGDPHSPVILCSYLPDEFIECEDPVDHVGNATASQELGYGCLKFGGQAYSDVEHTSVQCHALDGIECASPRTFLRENKPCIKYTGHYFITTLLYSFFLGCFGVDRFCLGHTGTAVGKLLTLGGLGIWWFVDLILLITGGLMPSDGSNWCTVY'),
                        ('ENSP00000265978',
                         'MERMNWLSRLASRGPGHRIPQGANLQTPVMADPETCLMVFKNHWSQVVRILERQGPRAAPGGADDLSAVRNHTYQMLTLLAEDRAVPSAPTGPGPLLEFALHEDLLTRVLTWQLQWDELGDGVEERRAEQLKLFEMLVSEARQPLLRHGPVREALLTLLDACGRPVPSSPALDEGLVLLLSQLCVCVAQEPSLLEFFLQPPPEPGAAPRLLLFSRLVPFVHREGTLGQQARDALLLLMALSAGSPTVGRYIADHSYFCPVLATGLSALYSSLPRKIEVPGDDWHCLRREDWLGVPALALFMSSLEFCNAVIQVAHPLVQKQLVDYIHNGFLVPVMGPALHKTSVEEMIASTAYLELFLRSISEPALLRTFLRFLLLHRHDTHTILDTLVARIGSNSRLCMVSLSLFRTLLNLSCEDVLLQLVLRYLVPCNHVMLSQKPAVRDVDLYGRAADKFLSLIPRCCRHHAPSPPRPEHASWARGGPSRETGRREDITGPGSPSVDSSSVTTVPRPSTPSRLALFLRQQSLGGSESPGPAPCSPGLSASPASSPGRRPTPAEEPGELEDNYLEYLREARRGVDRCVRACRTWSAPYDGERPSPEPSPFGSRTKKRSLLPEEDRNNVGEGEEEELGRRGRAGGAGEGPGHLPPPQLNGVPGSWPEGAKKVRLVPKEGAGELLEGISEGMAGLEGFGQELRELEVALSNGGTGSESPLEPPLPLEEEEAYESFTCPPEPPGPFLSSPLRTLNQLPSQPFTGPFMAVLFAKLENMLQNSVYVNFLLTGLVAQLACHPQPLLRSFLLNTNMVFQPSVKSLLQVLGSVKNKIENFAASQEDFPALLSKAKKYLIARGKLDWAEGPAAGPAPRRSDPLVKSRRPSLGELLLRHAHSPTRARQAAQLVLQPGRDGAGLGLSGGSPGASTPVLLTRGGAPERQGEALRVKNAVYCAVIFPEFLKELAAISQAHAVTSPFLLETSEEGSGPLISGCGPLNP'),
                        ('ENSP00000329127',
                         'MSSGTMKFNGYLRVRIGEAVGLQPTRWSLRHSLFKKGHQLLDPYLTVSVDQVRVGQTSTKQKTNKPTYNEEFCANVTDGGHLELAVFHETPLGYDHFVANCTLQFQELLRTTGASDTFEGWVDLEPEGKVFVVITLTGSFTEATLQRDRIFKHFTRKRQRAMRRRVHQINGHKFMATYLRQPTYCSHCREFIWGVFGKQGYQCQVCTCVVHKRCHHLIVTACTCQNNINKVDSKIAEQRFGINIPHKFSIHNYKVPTFCDHCGSLLWGIMRQGLQCKICKMNVHIRCQANVAPNCGVNAVELAKTLAGMGLQPGNISPTSKLVSRSTLRRQGKESSKEGNGIGVNSSNRLGIDNFEFIRVLGKGSFGKVMLARVKETGDLYAVKVLKKDVILQDDDVECTMTEKRILSLARNHPFLTQLFCCFQTPDRLFFVMEFVNGGDLMFHIQKSRRFDEARARFYAAEIISALMFLHDKGIIYRDLKLDNVLLDHEGHCKLADFGMCKEGICNGVTTATFCGTPDYIAPEILQEMLYGPAVDWWAMGVLLYEMLCGHAPFEAENEDDLFEAILNDEVVYPTWLHEDATGILKSFMTKNPTMRLGSLTQGGEHAILRHPFFKEIDWAQLNHRQIEPPFRPRIKSREDVSNFDPDFIKEEPVLTPIDEGHLPMINQDEFRNFSYVSPELQP'),
                        ('ENSP00000438264',
                         'MASVFHYFLLVLVFLDTHAAQPFCLPGCTCSEESFGRTLQCTSVSLGKIPGNLSEEFKQVRIENSPLFEMPQGSFINMSTLEYLWLNFNNISVIHLGALEHLPELRELRLEGNKLCSVPWTAFRATPLLRVLDLKRNKIDALPELALQFLVSLTYLDLSSNRLTVVSKSVFLNWPAYQKCRQPDCGAEILSSLVVALHDNPWVCDCRLRGLVQFVKSITLPVILVNSYLICQGPLSKAGQLFHETELSACMKPQISTPSANITIRAGQNVTLRCLAQASPSPSIAWTYPLSMWREFDGLLGGKHLTPVLTSSTGEDTALSELAIPAAHLVDSGNYTCMASNSIGKSNLVISLHVQPAQALHAPDSLSIPSEGNAYIDLRVVKQTVHGILLEWLAVADTSKEEWFTLYIASDEAFRKEVVHIGPGINTYAVDDLLPGTKYEACLSLEGQPPHQGQCVAFVTGRDAGGLEAREHLLHVTVVLCVVLLAVPVGAYAWAAQGPCSCSKWVLRGCLHRRKAPSCTPAAPQSKDGSFREHPAVCDDGEGHIDTEGDKEKGGTEDNS'),
                        ('ENSP00000298552',
                         'MAQQANVGELLAMLDSPMLGVRDDVTAVFKENLNSDRGPMLVNTLVDYYLETSSQPALHILTTLQEPHDKHLLDRINEYVGKAATRLSILSLLGHVIRLQPSWKHKLSQAPLLPSLLKCLKMDTDVVVLTTGVLVLITMLPMIPQSGKQHLLDFFDIFGRLSSWCLKKPGHVAEVYLVHLHASVYALFHRLYGMYPCNFVSFLRSHYSMKENLETFEEVVKPMMEHVRIHPELVTGSKDHELDPRRWKRLETHDVVIECAKISLDPTEASYEDGYSVSHQISARFPHRSADVTTSPYADTQNSYGCATSTPYSTSRLMLLNMPGQLPQTLSSPSTRLITEPPQATLWSPSMVCGMTTPPTSPGNVPPDLSHPYSKVFGTTAGGKGTPLGTPATSPPPAPLCHSDDYVHISLPQATVTPPRKEERMDSARPCLHRQHHLLNDRGSEEPPGSKGSVTLSDLPGFLGDLASEEDSIEKDKEEAAISRELSEITTAEAEPVVPRGGFDSPFYRDSLPGSQRKTHSAASSSQGASVNPEPLHSSLDKLGPDTPKQAFTPIDLPCGSADESPAGDRECQTSLETSIFTPSPCKIPPPTRVGFGSGQPPPYDHLFEVALPKTAHHFVIRKTEELLKKAKGNTEEDGVPSTSPMEVLDRLIQQGADAHSKELNKLPLPSKSVDWTHFGGSPPSDEIRTLRDQLLLLHNQLLYERFKRQQHALRNRRLLRKVIKAAALEEHNAAMKDQLKLQEKDIQMWKVSLQKEQARYNQLQEQRDTMVTKLHSQIRQLQHDREEFYNQSQELQTKLEDCRNMIAELRIELKKANNKVCHTELLLSQVSQKLSNSESVQQQMEFLNRQLLVLGEVNELYLEQLQNKHSDTTKEVEMMKAAYRKELEKNRSHVLQQTQRLDTSQKRILELESHLAKKDHLLLEQKKYLEDVKLQARGQLQAAESRYEAQKRITQVFELEILDLYGRLEKDGLLKKLEEEKAEAAEAAEERLDCCNDGCSDSMVGHNEEASGHNGETKTPRPSSARGSSGSRGGGGSSSSSSELSTPEKPPHQRAGPFSSRWETTMGEASASIPTTVGSLPSSKSFLGMKARELFRNKSESQCDEDGMTSSLSESLKTELGKDLGVEAKIPLNLDGPHPSPPTPDSVGQLHIMDYNETHHEHS'),
                        ('ENSP00000454973',
                         'MMASFQRSNSHDKVRRIVAEEGRTARNLIAWSVPLESKDDDGKPKCQTGGKSKRTIQGTHKTTKQSTAVDCKITSSTTGDKHFDKSPTKTRHPRKIDLRARYWAFLFDNLRRAVDEIYVTCESDQSVVECKEVLMMLDNYVRDFKALIDWIQLQEKLEKTDAQSRPTSLAWEVKKMSPGRHVIPSPSTDRINVTSNARRSLNFGGSTGTVPAPRLAPTGVSWADKVKAHHTGSTASSEITPAQSCPPMTVQKASRKNERKDAEGWETVQRGRPIRSRSTAVMPKVSLATEATRSKDDSDKENVCLLPDESIQKGQFVGDGTSNTIESHPKDSLHSCDHPLAEKTQFTVSTLDDVKNSGSIRDNYVRTSEISAVHIDTECVSVMLQAGTPPLQVNEEKFPAEKARIENEMDPSDISNSMAEVLAKKEELADRLEKANEEAIASAIAEEEQLTREIEAEENNDINIETDNDSDFSASMGSGSVSFCGMSMDWNDVLADYEARESWRQNTSWGDIVEEEPARPPGHGIHMHEKLSSPSRKRTIAESKKKHEEKQMKAQQLREKLREEKTLKLQKLLEREKDVRKWKEELLDQRRRMMEEKLLHAEFKREVQLQAIVKKAQEEEAKVNEIAFINTLEAQNKRHDVLSKLKEYEQRLNELQEERQRRQEEKQARDEAVQERKRALEAERQARVEELLMKRKEQEARIEQQRQEKEKAREDAARERARDREERLAALTAAQQEAMEELQKKIQLKHDESIRRHMEQIEQRKEKAAELSSGRHANTDYAPKLTPYERKKQCSLCNVLISSEVYLFSHVKGRKHQQAVRENTSIQGRELSDEEVEHLSLKKYIIDIVVESTAPAEALKDGEERQKNKKKAKKIKARMNFRAKEYESLMETKNSGSDSPYKAKLQRLAKDLLKQVQVQDSGSWANNKVSALDRTLGEITRILEKENVADQIAFQAAGGLTALEHILQAVVPATNVNTVLRIPPKSLCNAINVYNLTCNNCSENCSDVLFSNKITFLMDLLIHQLTVYVPDENNTILGRNTNKQVFEGLTTGLLKVSAVVLGCLIANRPDGNCQPATPKIPTQEMKNKPSQGDPFNNRVQDLISYVVNMGLIDKLCACFLSVQGPVDENPKMAIFLQHAAGLLHAMCTLCFAVTGRSYSIFDNNRQDPTGLTAALQATDLAGVLHMLYCVLFHGTILDPSTASPKENYTQNTIQVAIQSLRFFNSFAALHLPAFQSIVGAEGLSLAFRHMASSLLGHCSQVSCESLLHEVIVCVGYFTVNHPDNQVIVQSGRHPTVLQKLCQLPFQYFSDPRLIKVLFPSLIAACYNNHQNKIILEQEMSCVLLATFIQDLAQTPGQAENQPYQPKGKCLGSQDYLELANRFPQQAWEEARQFFLKKEKK'),
                        ('ENSP00000466399',
                         'MGVLRVGLCPGLTEEMIQLLRSHRIKTVVDLVSADLEEVAQKCGLSYKTWRAHSSGNLGGLQLPQVPAGRSWSGVRNALKKAGLGHGGTDGLSLNAFDERGTAVSTSRLDKLLDAGLYTGEVTEIVGGPGSGKTQVCLCMAANVAHGLQQNVLYVDSNGGLTASRLLQLLQAKTQDEEEQAEALRRIQVVHAFDIFQMLDVLQELRGTVAQQVTGSSGTVKVVVVDSVTAVVSPLLGGQQREGLALMMQLARELKTLARDLGMAVVVTNHITRDRDSGRLKPALGRSWSFVPSTRILLDTIEGAGASGGRRMACLAKSSRQPTGFQEMVDIGTWGTSEQSATLQGDQT'),
                        ('ENSP00000338130',
                         'MAVFKTTLWRLISGTLGIICLSLMSTLGILLKNSFTKLSIEPAFTPGPNIELQKDSDCCSCQEKWVGYRCNCYFISSEQKTWNESRHLCASQKSSLLQLQNTDELDFMSSSQQFYWIGLSYSEEHTAWLWENGSALSQYLFPSFETFNTKNCIAYNPNGNALDESCEDKNRYICKQQLI')]

    def test_datatype_to_moltype_seqtype(self, homology_table, datatype):
        data, moltype, seqtype = homology_table.datatype_to_moltype_seqtype(
            datatype)
        if datatype.endswith('peptide'):
            assert moltype == seqtype == 'protein'
            assert pdt.assert_almost_equal(data, homology_table.protein_coding)
        elif datatype.endswith('cdna'):
            assert moltype == "DNA"
            assert seqtype == 'cdna'
            assert pdt.assert_almost_equal(data, homology_table.protein_coding)
        elif datatype.endswith('cds'):
            assert moltype == "DNA"
            assert seqtype == 'cds'
            assert pdt.assert_almost_equal(data, homology_table.protein_coding)
        elif datatype == 'non_coding':
            assert moltype == "DNA"
            assert seqtype == 'cdna'
            assert pdt.assert_almost_equal(data, homology_table.non_coding)


def test_cli_tsv_all_pairs(species1, species2, homologues_tsv, homology_scores_allpairs):
    from khtools.homology import cli

    runner = CliRunner()
    result = runner.invoke(cli, ['--n-background', "2",
                                 species1, species2, homologues_tsv])
    assert result.exit_code == 0
    assert homology_scores_allpairs.to_csv() == result.stdout


def test_cli_tsv_n_subset5(species1, species2, homologues_tsv):
    from khtools.homology import cli

    runner = CliRunner()
    result = runner.invoke(cli, ['--n-subset', '5', "--n-background", "2",
                                 species1, species2, homologues_tsv])
    assert result.exit_code == 0


def test_cli_tsv_gz(species1, species2, homologues_tsv_gz):
    from khtools.homology import cli

    runner = CliRunner()
    result = runner.invoke(cli, ["--n-background", "2",
                                 species1, species2, homologues_tsv_gz])
    assert result.exit_code == 0

